#!/bin/bash
echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0;32m-        TRANSLATE BY PUKANG VPN      -\033[0m"
echo -e "\033[0;32m-              LINE ID : 0967379301           -\033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo ""
echo -e "\033[1;31mRESTARTING...\033[0m"
shutdown -r now